const PROJECTS = [
  {
    id: 1,
    name: 'pantocrator,',
    title: 'pantocrator | el gobierno de china',
    type: 'music video',
    year: '2021',
    producer: '.Futuro',
    creator: ' Martí Colomer & Nil Pagès',
    dop: 'Joan Agramunt',
    artDirection: 'Yannick Palahí',
    focus: 'Joaquim Vinyes',
    camAssistant: 'Maxym Visual',
    artAssistant: 'Alicia Bullich',
    productionAssistant: 'Guillem Salellas',
    car: 'Auto 3 Domeny',
    graphicDesigner: 'Aleix Planas',
    color: 'Biel Geli',
    compositing: 'Nacho Vaya',
    matte: 'Albert Palahí',
    editing: 'Adrià Expòsit & Martí Colomer',
    artSupplier: 'Art estudi & Seis Stud',
    link: 'https://player.vimeo.com/video/571717641',
    image: 'https://i.ibb.co/ZxdSyc8/PANTOCRATOR.jpg'
  },
  {
    id: 2,
    name: 'gaspar,',
    title: 'gaspar | no autotune ft lauren nine',
    type: 'music video',
    year: '2021',
    producer: '.Futuro',
    creator: ' Martí Colomer & Nil Pagès',
    dop: 'Joan Agramunt',
    artDirection: 'Yannick Palahí',
    focus: 'Joaquim Vinyes',
    camAssistant: 'Maxym Visual',
    artAssistant: 'Alicia Bullich',
    productionAssistant: 'Guillem Salellas',
    car: 'Auto 3 Domeny',
    graphicDesigner: 'Aleix Planas',
    color: 'Biel Geli',
    artSupplier: 'Art estudi',
    link: 'https://player.vimeo.com/video/461749664?badge=0&autopause=0&player_id=0&app_id=58479',
    image: 'https://i.ibb.co/YN7FLDw/gaspar.jpg'
  },
  {
    id: 3,
    name: 'honey cupons,',
    image: 'https://i.ibb.co/CtwP32B/honey.png'
  },
  {
    id: 4,
    name: 'herbert',
    title: 'herbert | shortfilm teaser',
    type: 'shortfilm',
    year: '2019 | 2020',
    description: 'Teaser was drawn up by financing plan for the short film Herbert (2020) which will soon be released at several national film festivals',
    director: 'Adrià Expòsit Goy',
    dop: 'Jordi Sánchez Prada',
    artDirection: 'Anna Albert & Yannick Palahí',
    music: 'Andreu Roig',
    color: 'Biel Geli',
    graphicDesigner: 'Alícia Bullich',
    link: 'https://player.vimeo.com/video/432920204',
    image: 'https://i.ibb.co/TmKqXLF/HERBERT.png'
  }
];

export default PROJECTS;
